.PHONY: all
all:
	make -C libvampyrtools
	make -C stb
	make -C con2bmp
	make -C bmp2con

.PHONY: clean
clean:
	make -C libvampyrtools clean
	make -C stb clean
	make -C con2bmp clean
	make -C bmp2con clean
