.PHONY: all
all:
	make -C libvampyrtools
	make -C con2bmp
	make -C bmp2con
	make -C splitss

.PHONY: clean
clean:
	make -C libvampyrtools clean
	make -C con2bmp clean
	make -C bmp2con clean
	make -C splitss clean
